### ISSUE TITLE
registerInternal call upgradeDomInternal without cssClass

### ISSUE THREAD

**Issue by HenriqueLimas** [jasonmayes/mdl-component-design-pattern#1]
Hi!

The `registerInternal` is calling the `upgradeDomInternal` without passing the `cssClass` params, but we already have this value, so why we can't pass this value? With that improve, we don't need to execute again the `findRegisteredClass_` inside the `upgradeDomInternal` class.

Before:

``` javascript
function registerInternal(config) {
    ...    
    upgradeDomInternal(config.classAsString);
}
```

After:

``` javascript
function registerInternal(config) {
    ...
    var found = findRegisteredClass_(config.classAsString, newConfig);
    ...

    upgradeDomInternal(config.classAsString, find.cssClass);
}
```

**Comment by jasonmayes** [comment]
A good catch, unless I am missing something (has been a while since I looked a this), but I think you are correct. We could actually use the following:

```
function registerInternal(config) {
    var newConfig = {
      'classConstructor': config.constructor,
      'className': config.classAsString,
      'cssClass': config.cssClass,
      'callbacks': []
    };

    var found = findRegisteredClass_(config.classAsString, newConfig);

    if (!found) {
      registeredComponents_.push(newConfig);
    }
    upgradeDomInternal(config.classAsString, config.cssClass);
}
```

If the component has not been registered yet, found would be false, hence we push on line 111 if it is not found. But the config contains all data required, so using that is safer.

**Comment by HenriqueLimas** [comment]
Yeah, with `config` is safer and correct, because using `found` it's really not safe. Thank's. :+1:
