### ISSUE TITLE
Question: How to update table views after dynamically adding rows?

### ISSUE THREAD

**Issue by jodusan** [jasonmayes/mdl-component-design-pattern#3]
Jason, I am not able to update MaterialDataTable view after I dynamically add some rows. Can you see any problem here?

http://stackoverflow.com/questions/37780219/how-to-update-table-view-in-html/37790542

Also, this mdl is amazing! I love it !

Thanks  
Dusan

**Comment by jasonmayes** [comment]
Thanks for the kind words, as you have probably realised by the fact this is closed, this belongs on the MDL repo :-) This repo was for the original design pattern for the component manager/upgrader when it first launched :-)
